language: python
python:
  - "2.7"

install:
  - pip install pep8

before_script:
  - pep8 --version

script:
  - pep8 config extras modules probe tests tools

notifications:
  email:
    on_success: never
